excluded:
  - .aidlc
  - .build
  - .derivedData
  - .deriveddata
  - BuildArtifacts

line_length:
  warning: 350
  error: 400

file_length:
  warning: 500
  error: 700

type_body_length:
  warning: 500
  error: 700

function_body_length:
  warning: 240
  error: 300

function_parameter_count:
  warning: 17
  error: 20

cyclomatic_complexity:
  warning: 22
  error: 30

large_tuple:
  warning: 5
  error: 8

type_name:
  max_length:
    warning: 60
    error: 80

identifier_name:
  min_length:
    warning: 2
    error: 1
